services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$root" ]
      timeout: 20s
      retries: 10
  ui:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

  app:
    build: ./app
    container_name: app
    environment:
      SQL_HOST: mysql
      SQL_PORT: 3306
      SQL_USER: root
      SQL_PASSWORD: root
      SQL_DB: digital_hunter
    ports:
      - "8000:8000"


volumes:
  mysql_data:
